config/routes.rb
Rails.application.routes.draw do
 
  resources :genres
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "movies#index"

  resources :movies do
    resources :reviews
    resources :favorites, only: [:create, :destroy]
  end

  get "signup" => "users#new"

  get "movies/filter/:filter" => "movies#index", as: :filtered_movies
  # The above can potentially be used to create a filter by tags, and by members you are following


  resource :session, only: [:new, :create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/characterization.rb
class Characterization < ApplicationRecord
  belongs_to :movie
  belongs_to :genre
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :movie
  belongs_to :user
end

app/models/genre.rb
class Genre < ApplicationRecord

	validates :name, presence: true, uniqueness: true

	# These two are related
	has_many :characterizations, dependent: :destroy
	has_many :movies, through: :characterizations

end

app/models/movie.rb
class Movie < ApplicationRecord

	before_save :set_slug

	has_many :reviews, dependent: :destroy
	has_many :favorites, dependent: :destroy
	has_many :fans, through: :favorites, source: :user
	
	# These two are related
	has_many :characterizations, dependent: :destroy
	has_many :genres, through: :characterizations


	validates :title, :released_on, presence: true
	validates :description, length: { minimum: 25 }
	validates :total_gross, numericality: { greater_than_or_equal_to: 0 }
	validates :image_file_name, format: {
		with: /\w+\.(jpg|png)\z/i,
		message: "must be a JPG or PNG image"
	}

  RATINGS = %w(G PG PG-13 R NC-17)
  validates :rating, inclusion: { in: RATINGS }

	def flop?
		total_gross < 225000000
	end

	scope :released, -> { where("released_on < ?", Time.now).order(released_on: :desc) }
	scope :upcoming, -> { where("released_on > ?", Time.now).order(released_on: :asc) }
	scope :recent, ->(max=5) { released.limit(max) }
	# or scope :recent, lambda { |max=5| released.limit(max) }

	def average_stars
		reviews.average(:stars) || 0.0
	end 

	def to_param
		slug
	end

	private

	def set_slug
		self.slug = title.parameterize
	end
	
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :movie
  belongs_to :user

  validates :comment, length: { minimum: 4 }
  
  STARS = [1, 2, 3, 4, 5]
  validates :stars, inclusion: {
    in: STARS,
    message: "Must be between 1 & 5"
  }

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_movies, through: :favorites, source: :movie

  validates :name, presence: true;
  validates :email, format: { with: /\S+@\S+/ },
                    uniqueness: { case_sensitive: false}

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

	before_action :require_sign_in 
	before_action :set_movie

	def create
		@movie.favorites.create!(user: current_user)
		redirect_to @movie
	end

	def destroy
		favorite = current_user.favorites.find(params[:id])
		favorite.destroy

		redirect_to @movie
	end

	def set_movie
  	@movie = Movie.find_by!(slug: params[:movie_id])
	end

end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

	before_action :require_sign_in, except: [:index, :show]
	before_action :require_admin, except: [:index, :show]
	before_action :set_movie, only: [:show, :edit, :update, :destroy]

	def index
		case params[:filter]
		when "upcoming"
			@movies = Movie.upcoming
		when "recent"
			@movies = Movie.recent
		else
			@movies = Movie.released
		end
		# This type of use of scopes and a case statement can be used to show filtered posts
		# by tags and by members you are following on Break Diving
	end


	def show
		@fans = @movie.fans
		@genres = @movie.genres
		if current_user
    	@favorite = current_user.favorites.find_by(movie_id: @movie.id)
  	end
	end

	def edit
	end

	def update
		if @movie.update(movie_params)
			redirect_to @movie, notice: "Movie updated successfully."
		else 
			render :edit
		end
	end

	def new
		@movie = Movie.new
	end

	def create
  	@movie = Movie.new(movie_params)
		if @movie.save
  		redirect_to @movie, notice: "Movie created successfully."
  	else
  		render :new
  	end
	end

	def destroy
		@movie.destroy
		redirect_to root_path, alert: "Movie successfully deleted."
	end

	private

	def movie_params
		params.require(:movie).permit(:title, :description, :rating, :released_on, 
																					:total_gross, :director, :duration, :image_file_name,
																					genre_ids: [])
	end	

	def set_movie
		@movie = Movie.find_by!(slug: params[:id])
	end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :require_sign_in
  before_action :set_movie

	def index
		@reviews = @movie.reviews
	end

	def new
		@review = @movie.reviews.new
	end

	def create
		@review = @movie.reviews.new(review_params)
		@review.user = current_user
		if @review.save
			redirect_to movie_reviews_path(@movie), notice: "Review created successfully."
		else
			render :new
		end
	end

	private

	def review_params
		params.require(:review).permit(:stars, :comment)
	end

	def set_movie
  	@movie = Movie.find_by!(slug: params[:movie_id])
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


	def new
	end

	def create
		user = User.find_by(email: params[:email])
		if user && user.authenticate(params[:password])
			session[:user_id] = user.id
      redirect_to (session[:intended_url] || user), 
      							notice: "Welcome back, #{user.name}!"
      session[:intended_url] = nil
  	else
  		flash.now[:alert] = "Invalid email/password combination!"
      render :new
  	end
	end

	def destroy
		session[:user_id] = nil
		redirect_to movies_url, notice: "You're now signed out!"
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :require_sign_in, except: [:new, :create]
	before_action :require_correct_user, only: [:edit, :update, :destroy]
	before_action :require_admin, only: [:destroy]

	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
		@reviews = @user.reviews
		@favorite_movies = @user.favorite_movies
	end

	def new
		@user = User.new
	end

	def create
  	@user = User.new(user_params)
  	if @user.save
  		session[:user_id] = @user.id
    	redirect_to @user, notice: "Thanks for signing up!"
  	else
    	render :new
  	end
	end

	def edit
	end

	def update
		if @user.update(user_params)
			redirect_to @user, notice: "Successfully updated!"
		else
			render :edit
		end
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy
		redirect_to movies_url, alert: "Account successfully deleted!"
	end

	private

	def user_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation)
	end

	def require_correct_user
		@user = User.find(params[:id])
		redirect_to root_url unless current_user?(@user)
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper

	def fav_or_unfave_button(movie, favorite)
	  if favorite
	    button_to "♡ Unfave", movie_favorite_path(movie, favorite), method: :delete
	  else
	    button_to "♥️ Fave", movie_favorites_path(movie)
	  end
	end

end

# Helpers use raw ruby code.  No Ruby html
# Helpers are methods that you call from the show page to avoid logic overload within the view

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/movies_helper.rb
module MoviesHelper

	def total_gross(movie)
		if movie.flop?
			return "flop"
		else
			number_to_currency(movie.total_gross, precision: 0)
		end
	end

	def year_of(movie)
		if movie.released_on
			movie.released_on.year
		else
			"No Date"
		end
	end

end

app/helpers/reviews_helper.rb
module ReviewsHelper

	def average_stars(movie)
  	if movie.average_stars.zero?
    	content_tag(:strong, "No reviews")
  	else
    	pluralize(number_with_precision(movie.average_stars, precision: 1), "star")
  	end
	end

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |type, message| %>
  <%= content_tag(:div, message, class: "flash #{type}") %>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <p>
    Copyright &copy; 2020-<%= Time.now.year %>
  </p>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav>
    <%= link_to image_tag("logo.png"), movies_path %>

      <ul>
        <% if current_user %>
          <li>
            <%= link_to current_user.name, user_path(current_user.id) %>
          </li>
          <li style="list-style-type: none;">
            <%= link_to "Released Movies", movies_path %>
          </li>
          <li style="list-style-type: none;">
            <%= link_to "Upcoming Movies", filtered_movies_path(:upcoming) %>
          </li>
          <li style="list-style-type: none;">
            <%= link_to "Recent Movies", filtered_movies_path(:recent) %>
          </li>
          <% if current_user_admin? %>
            <li style="list-style-type: none;">
              <%= link_to "New Movie", new_movie_path %>
            </li>
          <% end %>
          <%= link_to "Sign Out", session_path, method: :delete, class: "button" %>
        <% else %>
          <li>
            <%= link_to "Sign In", new_session_path, class: "button" %>
          </li>
          <%= link_to "Sign Up", signup_path, class: "button" %>
        <% end %>
      </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flix</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   
  <%= render "layouts/header" %>
  <%= render "layouts/flash" %>
  
  <div class="content">
    <%= yield %>
  </div>

  <%= render "layouts/footer" %>

  </body>
</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <section class="errors">
    <h2>
      Oops! Your form could not be saved.
    </h2>
    <h3>
      Please correct the following
      <%= pluralize(object.errors.size, "error") %>:
    </h3>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </section>
<% end %>